import { ImovelComFotos } from '@/types'

export const mockImoveis: ImovelComFotos[] = [
    {
        id: '1',
        slug: 'casa-espetacular-jardins',
        titulo: 'Casa Espetacular com Piscina',
        descricao: 'Uma belíssima casa localizada no coração dos Jardins. Conta com área de lazer completa, piscina aquecida, churrasqueira e amplo jardim. Perfeita para receber amigos e família.',
        tipo: 'residencial',
        finalidade: 'venda',
        preco: 3500000,
        area_m2: 450,
        quartos: 4,
        banheiros: 5,
        vagas: 4,
        endereco: 'Rua das Flores, 123',
        bairro: 'Jardins',
        cidade: 'São Paulo',
        uf: 'SP',
        cep: '01422-000',
        latitude: -23.56168,
        longitude: -46.65598,
        destaque: true,
        status: 'ativo',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        imovel_fotos: [
            { id: 'f1', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=1600', ordem: 0, imovel_id: '1', created_at: new Date().toISOString() },
            { id: 'f2', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1600', ordem: 1, imovel_id: '1', created_at: new Date().toISOString() },
            { id: 'f3', url: 'https://images.unsplash.com/photo-1600607687931-cecebd808cbd?auto=format&fit=crop&q=80&w=1600', ordem: 2, imovel_id: '1', created_at: new Date().toISOString() }
        ]
    },
    {
        id: '2',
        slug: 'apartamento-moderno-paulista',
        titulo: 'Apartamento Moderno e Mobiliado',
        descricao: 'Apartamento recém-reformado, com móveis planejados de alto padrão. Localização privilegiada, a duas quadras da Av. Paulista, próximo a metrô, shoppings e hospitais.',
        tipo: 'residencial',
        finalidade: 'locação',
        preco: 6500,
        area_m2: 85,
        quartos: 2,
        banheiros: 2,
        vagas: 1,
        endereco: 'Alameda Santos, 1000',
        bairro: 'Bela Vista',
        cidade: 'São Paulo',
        uf: 'SP',
        cep: '01418-100',
        latitude: -23.56388,
        longitude: -46.65348,
        destaque: true,
        status: 'ativo',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        imovel_fotos: [
            { id: 'f4', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1600', ordem: 0, imovel_id: '2', created_at: new Date().toISOString() },
            { id: 'f5', url: 'https://images.unsplash.com/photo-1502672260266-1c1c24240f38?auto=format&fit=crop&q=80&w=1600', ordem: 1, imovel_id: '2', created_at: new Date().toISOString() }
        ]
    },
    {
        id: '3',
        slug: 'sala-comercial-faria-lima',
        titulo: 'Laje Corporativa Alto Padrão',
        descricao: 'Excelente vão livre em um dos prédios mais cobiçados da Faria Lima. Certificação LEED, piso elevado, ar condicionado central e 10 vagas de garagem.',
        tipo: 'comercial',
        finalidade: 'locação',
        preco: 25000,
        area_m2: 300,
        quartos: 0,
        banheiros: 4,
        vagas: 10,
        endereco: 'Av. Brigadeiro Faria Lima, 3000',
        bairro: 'Itaim Bibi',
        cidade: 'São Paulo',
        uf: 'SP',
        cep: '01451-001',
        latitude: -23.58668,
        longitude: -46.68218,
        destaque: true,
        status: 'ativo',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        imovel_fotos: [
            { id: 'f6', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1600', ordem: 0, imovel_id: '3', created_at: new Date().toISOString() }
        ]
    },
    {
        id: '4',
        slug: 'cobertura-duplex-leblon',
        titulo: 'Cobertura Duplex com Vista Mar',
        descricao: 'Incrível cobertura reformada com vista panorâmica pro mar. Terraço espaçoso com piscina privativa, deck de madeira e espaço gourmet.',
        tipo: 'residencial',
        finalidade: 'venda',
        preco: 8900000,
        area_m2: 280,
        quartos: 3,
        banheiros: 4,
        vagas: 3,
        endereco: 'Av. Delfim Moreira',
        bairro: 'Leblon',
        cidade: 'Rio de Janeiro',
        uf: 'RJ',
        cep: '22441-000',
        latitude: -22.98668,
        longitude: -43.22018,
        destaque: false,
        status: 'ativo',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        imovel_fotos: [
            { id: 'f7', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1600', ordem: 0, imovel_id: '4', created_at: new Date().toISOString() }
        ]
    }
]
